name: 01. Deploy to Production

permissions:
  id-token: write
  contents: read

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy-production:
    name: Deploy to production
    concurrency:
      group: production_environment
      cancel-in-progress: true
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://jetrockets.com
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_branch }}

      - uses: ./.github/workflows/setup
        name: Setup
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Kamal Deploy
        uses: ./.github/workflows/kamal-deploy
        with:
          kamal-registry-username: ${{ secrets.DIGITAL_OCEAN_ACCESS_TOKEN }}
          kamal-registry-password: ${{ secrets.DIGITAL_OCEAN_ACCESS_TOKEN }}
          database-url: ${{ secrets.DATABASE_URL }}
          redis-url: ${{ secrets.REDIS_URL }}
          rails-master-key: ${{ secrets.RAILS_MASTER_KEY }}
          pg-hero-username: ${{ secrets.PGHERO_USERNAME }}
          pg-hero-password: ${{ secrets.PGHERO_PASSWORD }}
          environment: production