name: Kamal Deploy

inputs:
  environment:
    description: 'Environment'
    required: true
  kamal-registry-username:
    description: 'Kamal Registry Username (Digital Ocean Access Token)'
    required: true
  kamal-registry-password:
    description: 'Kamal Registry Password (Digital Ocean Access Token)'
    required: true
  database-url:
    description: Database URL
    required: true
  redis-url:
    description: Redis URL
    required: true
  rails-master-key:
    description: Rails Master Key
    required: true

runs:
  using: composite
  steps:
    - name: Kamal Deploy
      shell: bash
      id: kamal-deploy
      env :
        KAMAL_REGISTRY_USERNAME: ${{ inputs.kamal-registry-username }}
        KAMAL_REGISTRY_PASSWORD: ${{ inputs.kamal-registry-password }}
        DATABASE_URL: ${{ inputs.database-url }}
        REDIS_URL: ${{ inputs.redis-url }}
        RAILS_MASTER_KEY: ${{ inputs.rails-master-key }}
        DOCKER_BUILDKIT: 1
      run: |
        ./bin/kamal deploy --destination=${{ inputs.environment }}

    - name: Kamal release on cancel
      shell: bash
      if: ${{ cancelled() }}
      run: |
        ./bin/kamal lock release --destination=${{ inputs.environment }}